steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.pay-gateway
      - -t
      - asia-northeast3-docker.pkg.dev/project-64269e62-555d-4979-88e/solvamos-img/pay-gateway:latest
      - .
images:
  - asia-northeast3-docker.pkg.dev/project-64269e62-555d-4979-88e/solvamos-img/pay-gateway:latest
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
