steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.pay-gateway
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/pay-gateway:${_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/pay-gateway:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/pay-gateway

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/pay-gateway:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/pay-gateway:latest

substitutions:
  _REGION: asia-northeast3
  _REPO: solvamos-img
  _TAG: manual

options:
  logging: CLOUD_LOGGING_ONLY

